# .gitlab-ci.yml file
default:
  image: node:16
  tags:
    - docker

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

stages:
  - test
  - build
  - scan

test:
  stage: test
  script:
    - npm clean-install
  rules:
    - when: always
      allow_failure: false
build:
  stage: build
  script:
    - /bin/bash bin/package.sh
  needs:
    - test
  artifacts:
    untracked: false
    when: on_success
    expire_in: "30 days"
    paths:
      - dependencies.tar.gz
      - prism_api.tar.gz
scan:
  stage: scan
  image: eclipse-temurin:17
  needs:
    - build
  before_script:
    - apt update
    - apt install unzip
  script:
    - /bin/bash bin/blackduck.sh
    - /bin/bash bin/veracode.sh
  artifacts:
    untracked: false
    when: always
    expire_in: "30 days"
    paths:
      - results.json
      - filtered_results.json