# .gitlab-ci.yml file
default:
  image: node:16
  tags:
    - docker

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

stages:
  - test
  - scan

test:
  stage: test
  script:
    - npm clean-install
  rules:
    - when: always
      allow_failure: false
scan:
  stage: scan
  image: eclipse-temurin:17
  needs:
    - build
  script:
    - /bin/bash bin/blackduck.sh